name: assistantapp
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  alan_voice: ^2.0.15
  audioplayers: ^0.18.3
  cloud_firestore: ^1.0.5
  cupertino_icons: ^1.0.2
  dio: ^4.0.0
  eva_icons_flutter: ^3.0.0
  fab_menu_items: ^1.0.0
  firebase_auth: ^1.1.1
  firebase_core: ^1.0.4
  firebase_database: ^6.1.2
  firebase_messaging: ^9.1.4
  flutter_icons: ^1.1.0
  flutter_signin_button: ^2.0.0
  flutter_svg: ^0.22.0
  font_awesome_flutter: ^9.0.0
  get: ^4.1.4
  google_sign_in: ^5.0.2
  http: ^0.13.3
  intl: ^0.17.0
  lipsum: ^1.0.1
  material_design_icons_flutter: ^4.0.5955
  md2_tab_indicator: ^1.0.2
  shared_preferences: ^2.0.5
  syncfusion_flutter_charts: ^19.1.59
  url_launcher: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - images/h.gif
    - images/Aquaponics.png
    - images/temperature.png
    - images/humidity.png
    - images/tempeau.png
    - images/ph.png
    - images/fish2.png
    - images/fish1.png
    - images/fish0.png
    - images/plant0.png
    - images/plant1.png
    - images/plant2.png
    - images/plant3.png
    # An image asset can refer to one or more resolution-specific "variants", see
    # https://flutter.dev/assets-and-images/#resolution-aware.
    # For details regarding adding assets from package dependencies, see
    # https://flutter.dev/assets-and-images/#from-packages
    # To add custom fonts to your application, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # example:
  fonts:
    - family: Application1
      fonts:
        - asset: images/Application1.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
